/**
 * Type definitions for the AI Game Master system in The Arcane Codex
 * This module defines all types related to dynamic scenario generation,
 * player choices, consequences, and asymmetric information management.
 */

import { God, CharacterClass } from './game';

/**
 * Types of scenarios that can be generated by the AI GM
 */
export enum ScenarioType {
  /** Divine beings testing or questioning the party */
  DIVINE_INTERROGATION = 'DIVINE_INTERROGATION',
  /** Situations requiring difficult ethical choices */
  MORAL_DILEMMA = 'MORAL_DILEMMA',
  /** Allies or NPCs turning against the party */
  BETRAYAL = 'BETRAYAL',
  /** Finding hidden knowledge, artifacts, or secrets */
  DISCOVERY = 'DISCOVERY',
  /** Combat situations with strategic choices */
  COMBAT_CHOICE = 'COMBAT_CHOICE',
  /** Diplomatic or trade negotiations */
  NEGOTIATION = 'NEGOTIATION',
  /** Mystery-solving or clue-gathering scenarios */
  INVESTIGATION = 'INVESTIGATION'
}

/**
 * Types of consequences that can result from player choices
 */
export enum ConsequenceType {
  /** Happens immediately after the choice */
  IMMEDIATE = 'IMMEDIATE',
  /** Occurs within the next few scenarios */
  SHORT_TERM = 'SHORT_TERM',
  /** Affects the long-term narrative */
  LONG_TERM = 'LONG_TERM',
  /** Changes the overall world state */
  WORLD_STATE = 'WORLD_STATE'
}

/**
 * Represents a faction in the game world
 */
export interface Faction {
  id: string;
  name: string;
  reputation: number; // -100 to 100
  description: string;
  isSecret?: boolean;
}

/**
 * Tracks major events that have occurred in the game world
 */
export interface WorldEvent {
  id: string;
  timestamp: number;
  type: string;
  description: string;
  affectedFactions?: string[];
  triggeredBy?: string[]; // player IDs
  visibility: 'PUBLIC' | 'PARTIAL' | 'HIDDEN';
}

/**
 * Global state of the game world
 */
export interface WorldState {
  /** Faction standings and relationships */
  factions: Map<string, Faction>;
  /** Major events that have shaped the world */
  majorEvents: WorldEvent[];
  /** History of significant player actions */
  playerActionsHistory: PlayerAction[];
  /** Current time/season in the game world */
  worldTime: {
    day: number;
    season: 'SPRING' | 'SUMMER' | 'FALL' | 'WINTER';
    year: number;
  };
  /** Global flags that affect scenario generation */
  globalFlags: Map<string, boolean | number | string>;
}

/**
 * Records a significant player action
 */
export interface PlayerAction {
  playerId: string;
  scenarioId: string;
  choiceId: string;
  timestamp: number;
  impact: 'MINOR' | 'MODERATE' | 'MAJOR' | 'CRITICAL';
  description: string;
}

/**
 * Player-specific information and history
 */
export interface PlayerHistory {
  playerId: string;
  playerName: string;
  characterClass: CharacterClass;
  /** Favor levels with each god */
  godFavor: Map<God, number>;
  /** Personal inventory of special items */
  specialItems: string[];
  /** Personal relationships with NPCs */
  npcRelationships: Map<string, number>;
  /** Secrets this player has discovered */
  knownSecrets: string[];
  /** Player's personal goals */
  personalGoals: string[];
  /** Tracking moral alignment */
  moralAlignment: {
    lawChaos: number; // -100 (chaos) to 100 (law)
    goodEvil: number; // -100 (evil) to 100 (good)
  };
}

/**
 * Current state of the party
 */
export interface PartyState {
  /** Current location in the world */
  location: string;
  /** Active quests */
  activeQuests: Quest[];
  /** Shared party inventory */
  sharedInventory: string[];
  /** Party's collective reputation */
  partyReputation: number;
  /** Current party resources */
  resources: {
    gold: number;
    supplies: number;
    influence: number;
  };
  /** Active buffs or debuffs */
  partyModifiers: StatusModifier[];
}

/**
 * Represents a quest or objective
 */
export interface Quest {
  id: string;
  title: string;
  description: string;
  objectives: QuestObjective[];
  reward?: string;
  deadline?: number; // World time day number
  giver?: string; // NPC or faction
  priority: 'MAIN' | 'SIDE' | 'HIDDEN';
}

/**
 * Individual quest objective
 */
export interface QuestObjective {
  id: string;
  description: string;
  completed: boolean;
  hidden?: boolean;
  revealCondition?: string;
}

/**
 * Status effects affecting the party
 */
export interface StatusModifier {
  id: string;
  name: string;
  description: string;
  duration: number; // Scenarios remaining
  effect: string;
}

/**
 * Context for scenario generation
 */
export interface ScenarioContext {
  /** History and state of all players */
  playerHistories: PlayerHistory[];
  /** Current state of the party */
  partyState: PartyState;
  /** Composition of the party */
  partyComposition: {
    playerIds: string[];
    classes: CharacterClass[];
    averageLevel: number;
    partySize: number;
  };
  /** Current world state */
  worldState: WorldState;
  /** ID of the previous scenario */
  previousScenarioId?: string;
  /** Current narrative arc */
  narrativeArc?: string;
  /** Environmental factors */
  environment?: {
    timeOfDay: 'DAWN' | 'MORNING' | 'AFTERNOON' | 'EVENING' | 'NIGHT' | 'MIDNIGHT';
    weather: 'CLEAR' | 'CLOUDY' | 'RAIN' | 'STORM' | 'SNOW' | 'FOG';
    terrain: string;
  };
}

/**
 * Request to generate a new scenario
 */
export interface ScenarioRequest {
  /** Full context for generation */
  context: ScenarioContext;
  /** Desired type of scenario (optional) */
  desiredType?: ScenarioType;
  /** Difficulty level 1-10 */
  difficulty: number;
  /** Player-specific information to consider */
  playerSpecificInfo?: {
    focusPlayerId?: string;
    playerTensions?: Array<{
      player1Id: string;
      player2Id: string;
      tensionLevel: number;
    }>;
  };
  /** Optional theme or mood */
  theme?: string;
  /** Whether to allow PvP elements */
  allowPvP?: boolean;
  /** Maximum time for scenario (in minutes) */
  timeLimit?: number;
}

/**
 * A choice available to players in a scenario
 */
export interface ScenarioChoice {
  id: string;
  /** Display text for the choice */
  text: string;
  /** Requirements to select this choice */
  requirements?: ChoiceRequirement[];
  /** Hidden consequences of this choice */
  hiddenConsequences: Consequence[];
  /** Skill checks required */
  skillChecks?: SkillCheck[];
  /** Whether this choice is visible to all players */
  visibility: 'ALL' | 'SPECIFIC' | 'CONDITIONAL';
  /** Players who can see this choice */
  visibleTo?: string[];
  /** Emotional tone of the choice */
  tone?: 'AGGRESSIVE' | 'DIPLOMATIC' | 'CAUTIOUS' | 'CLEVER' | 'NOBLE' | 'SELFISH';
}

/**
 * Requirements for a choice to be available
 */
export interface ChoiceRequirement {
  type: 'CLASS' | 'ITEM' | 'FAVOR' | 'STAT' | 'QUEST' | 'SECRET';
  value: string | number;
  comparison?: 'EQ' | 'GT' | 'LT' | 'GTE' | 'LTE' | 'HAS';
  playerId?: string; // Specific player requirement
}

/**
 * Skill check for a choice
 */
export interface SkillCheck {
  skill: string;
  difficulty: number;
  playerId?: string; // Specific player must pass
  consequences: {
    success: Consequence[];
    failure: Consequence[];
  };
}

/**
 * Consequence of a player choice
 */
export interface Consequence {
  id: string;
  /** Type of consequence */
  type: ConsequenceType;
  /** Description of what happens */
  description: string;
  /** Effect on player/party stats */
  statEffects?: StatEffect[];
  /** Effect on world state */
  worldEffects?: WorldEffect[];
  /** When this consequence is revealed */
  revealConditions: RevealCondition[];
  /** Target of the consequence */
  target: 'SELF' | 'PARTY' | 'SPECIFIC_PLAYER' | 'WORLD' | 'NPC';
  targetId?: string;
  /** Severity of the consequence */
  severity: 'TRIVIAL' | 'MINOR' | 'MODERATE' | 'MAJOR' | 'CRITICAL';
}

/**
 * Effect on player or party statistics
 */
export interface StatEffect {
  stat: string;
  modifier: number;
  duration?: number; // Scenarios
  stacks?: boolean;
}

/**
 * Effect on the world state
 */
export interface WorldEffect {
  type: 'FACTION_REP' | 'SPAWN_EVENT' | 'UNLOCK_LOCATION' | 'SPAWN_NPC' | 'MODIFY_QUEST' | 'SET_FLAG';
  target: string;
  value: any;
}

/**
 * Conditions for revealing information
 */
export interface RevealCondition {
  type: 'IMMEDIATE' | 'DELAYED' | 'ON_EVENT' | 'ON_DISCOVERY' | 'NEVER';
  value?: string | number;
  playerId?: string; // Specific player sees this
}

/**
 * Asymmetric information for a specific player
 */
export interface AsymmetricInfo {
  /** Player this information is for */
  playerId: string;
  /** Knowledge only this player has */
  hiddenKnowledge: HiddenKnowledge[];
  /** Clues visible only to this player */
  privateClues: Clue[];
  /** Deductions this player can make */
  availableDeductions: Deduction[];
  /** Private objectives for this player */
  privateObjectives?: PrivateObjective[];
  /** Information this player must NOT know */
  hiddenFromPlayer?: string[];
}

/**
 * Hidden knowledge a player possesses
 */
export interface HiddenKnowledge {
  id: string;
  type: 'SECRET' | 'OBSERVATION' | 'MEMORY' | 'INTUITION' | 'DIVINE_WHISPER';
  content: string;
  source: string;
  reliability: number; // 0-100
  canShare: boolean;
  expiresAt?: number; // World time
}

/**
 * A clue for investigation
 */
export interface Clue {
  id: string;
  description: string;
  category: 'PHYSICAL' | 'TESTIMONIAL' | 'MAGICAL' | 'DOCUMENTARY' | 'BEHAVIORAL';
  linkedTo?: string[]; // Other clue IDs
  requiredToProgress?: boolean;
}

/**
 * A deduction a player can make
 */
export interface Deduction {
  id: string;
  description: string;
  requiredClues: string[];
  confidence: number; // 0-100
  isCorrect?: boolean;
}

/**
 * Private objective for a player
 */
export interface PrivateObjective {
  id: string;
  description: string;
  reward: string;
  conflictsWith?: string[]; // Other player objectives
  deadline?: number;
}

/**
 * Complete response from scenario generation
 */
export interface ScenarioResponse {
  /** Unique identifier for this scenario */
  id: string;
  /** Type of scenario generated */
  type: ScenarioType;
  /** Title of the scenario */
  title: string;
  /** Main narrative text */
  narrative: string;
  /** Atmospheric description */
  atmosphere?: string;
  /** Available choices (2-4) */
  choices: ScenarioChoice[];
  /** Hidden consequences not immediately visible */
  hiddenConsequences: Consequence[];
  /** Asymmetric information per player */
  asymmetricInfo: AsymmetricInfo[];
  /** Time pressure (if any) */
  timeLimit?: number;
  /** Success conditions */
  successConditions?: SuccessCondition[];
  /** Failure conditions */
  failureConditions?: FailureCondition[];
  /** NPCs present in the scenario */
  npcs?: NPC[];
  /** Environmental hazards */
  hazards?: EnvironmentalHazard[];
  /** Potential rewards */
  rewards?: Reward[];
  /** Scenario-specific rules */
  specialRules?: string[];
  /** Hints for the human GM */
  gmNotes?: string;
}

/**
 * Condition for scenario success
 */
export interface SuccessCondition {
  id: string;
  description: string;
  type: 'ALL_SURVIVE' | 'OBJECTIVE_COMPLETE' | 'ITEM_OBTAINED' | 'NPC_SAVED' | 'CUSTOM';
  value?: any;
  partial?: boolean; // Allow partial success
}

/**
 * Condition for scenario failure
 */
export interface FailureCondition {
  id: string;
  description: string;
  type: 'TIME_LIMIT' | 'PARTY_WIPE' | 'OBJECTIVE_FAILED' | 'NPC_DIED' | 'CUSTOM';
  value?: any;
}

/**
 * Non-player character in a scenario
 */
export interface NPC {
  id: string;
  name: string;
  role: 'ALLY' | 'ENEMY' | 'NEUTRAL' | 'UNKNOWN';
  description: string;
  dialogue?: string[];
  attitude: number; // -100 to 100
  canNegotiate: boolean;
  secrets?: string[];
}

/**
 * Environmental hazard in a scenario
 */
export interface EnvironmentalHazard {
  id: string;
  name: string;
  description: string;
  triggerCondition: string;
  effect: string;
  avoidanceMethod?: string;
}

/**
 * Reward from a scenario
 */
export interface Reward {
  id: string;
  type: 'ITEM' | 'GOLD' | 'FAVOR' | 'REPUTATION' | 'INFORMATION' | 'ALLY';
  value: any;
  description: string;
  recipient: 'ALL' | 'SPECIFIC' | 'RANDOM' | 'CHOOSER';
  recipientId?: string;
}

/**
 * Template for fallback scenario generation
 */
export interface ScenarioTemplate {
  id: string;
  type: ScenarioType;
  title: string;
  narrativeTemplate: string;
  variables: TemplateVariable[];
  choiceTemplates: ChoiceTemplate[];
  minimumPlayers: number;
  maximumPlayers: number;
  difficultyRange: { min: number; max: number };
  tags: string[];
}

/**
 * Variable in a scenario template
 */
export interface TemplateVariable {
  name: string;
  type: 'STRING' | 'NUMBER' | 'PLAYER_NAME' | 'LOCATION' | 'NPC_NAME' | 'ITEM';
  options?: any[];
  generator?: string; // Function name to generate value
}

/**
 * Choice template for scenarios
 */
export interface ChoiceTemplate {
  id: string;
  textTemplate: string;
  consequenceTemplates: ConsequenceTemplate[];
  requirementTemplates?: string[];
}

/**
 * Consequence template
 */
export interface ConsequenceTemplate {
  type: ConsequenceType;
  descriptionTemplate: string;
  effects: string[];
}

/**
 * Active scenario being played
 */
export interface ActiveScenario {
  scenario: ScenarioResponse;
  startTime: number;
  playerChoices: Map<string, string>; // playerId -> choiceId
  revealed: Set<string>; // Revealed consequence IDs
  completed: boolean;
  outcome?: 'SUCCESS' | 'FAILURE' | 'PARTIAL' | 'ABANDONED';
}

/**
 * Configuration for the AI GM system
 */
export interface AIGMConfig {
  /** Enable AI generation vs templates only */
  enableAI: boolean;
  /** Maximum retries for AI generation */
  maxRetries: number;
  /** Timeout for AI requests (ms) */
  timeout: number;
  /** Fallback to templates on error */
  fallbackToTemplates: boolean;
  /** Logging level */
  logLevel: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';
  /** Cache scenarios for reuse */
  cacheScenarios: boolean;
  /** Maximum cached scenarios */
  maxCacheSize: number;
}

/**
 * Metrics for AI GM performance
 */
export interface AIGMMetrics {
  totalScenariosGenerated: number;
  aiGeneratedCount: number;
  templateGeneratedCount: number;
  averageGenerationTime: number;
  failureRate: number;
  playerSatisfactionScore?: number;
}